services:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: c4tt0dicenotes
      POSTGRES_PASSWORD: psqldicenotesapardo104
      POSTGRES_DB: dicenotes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--appendfilename", "appendonly.aof", "--dir", "/data"]

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env.docker
    environment:
      DJANGO_SETTINGS_MODULE: dicenotes.settings
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend

volumes:
  postgres_data:
  redis_data:
