# Generated by Django 5.1.2 on 2025-05-01 16:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alineamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_fijo', models.IntegerField(blank=True, null=True)),
                ('puntaje_dados', models.CharField(blank=True, max_length=10, null=True)),
                ('alcance', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion_corta', models.TextField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, default='campanas/default_campana.jpg', null=True, upload_to='campanas/')),
                ('descripcion_larga', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.CharField(blank=True, max_length=50, null=True)),
                ('usos', models.PositiveIntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado')], default='programado', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enemigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tamano', models.CharField(blank=True, max_length=50, null=True)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('armadura', models.IntegerField(blank=True, null=True)),
                ('puntos_vida', models.IntegerField(blank=True, null=True)),
                ('puntaje_fijo', models.CharField(blank=True, max_length=50, null=True)),
                ('puntaje_dados', models.CharField(blank=True, max_length=50, null=True)),
                ('velocidad', models.CharField(blank=True, max_length=50, null=True)),
                ('fuerza', models.IntegerField(blank=True, null=True)),
                ('destreza', models.IntegerField(blank=True, null=True)),
                ('constitucion', models.IntegerField(blank=True, null=True)),
                ('inteligencia', models.IntegerField(blank=True, null=True)),
                ('sabiduria', models.IntegerField(blank=True, null=True)),
                ('carisma', models.IntegerField(blank=True, null=True)),
                ('dificultad', models.IntegerField(blank=True, null=True)),
                ('bono_competencia', models.IntegerField(blank=True, null=True)),
                ('xp', models.IntegerField(blank=True, null=True)),
                ('sentidos', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='enemigos/')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ropa', 'Ropa'), ('accesorio', 'Accesorio'), ('ligera', 'Armadura ligera'), ('media', 'Armadura media'), ('pesada', 'Armadura pesada'), ('otro', 'Otro')], max_length=50)),
                ('puntaje_fijo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hechizo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.PositiveIntegerField(blank=True, null=True)),
                ('escuela', models.CharField(choices=[('abjuracion', 'Abjuración (Protección y disipación)'), ('adivinacion', 'Adivinación (Conocimiento y visión)'), ('conjuracion', 'Conjuración (Invocación y teletransporte)'), ('encantamiento', 'Encantamiento (Control mental y persuasión)'), ('evocacion', 'Evocación (Daño elemental y energía)'), ('ilusion', 'Ilusión (Engaño y manipulación de la realidad)'), ('nigromancia', 'Nigromancia (Muerte y manipulación de almas)'), ('transmutacion', 'Transmutación (Cambio de formas y materiales)')], max_length=100)),
                ('informacion', models.TextField(blank=True, max_length=2000, null=True)),
                ('alcance', models.CharField(blank=True, max_length=50, null=True)),
                ('duracion', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempo_lanzamiento', models.CharField(blank=True, max_length=50, null=True)),
                ('efecto', models.CharField(blank=True, max_length=50, null=True)),
                ('usos', models.PositiveIntegerField(blank=True, null=True)),
                ('valor', models.PositiveIntegerField(blank=True, null=True)),
                ('puntaje_fijo', models.IntegerField(blank=True, null=True)),
                ('puntaje_dados', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenCampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='img_campanas/')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('oro', models.PositiveIntegerField(default=0)),
                ('plata', models.PositiveIntegerField(default=0)),
                ('cobre', models.PositiveIntegerField(default=0)),
                ('electrum', models.PositiveIntegerField(default=0)),
                ('platino', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioPersonaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('equipado', models.BooleanField(default=False)),
                ('oro', models.PositiveIntegerField(default=0)),
                ('plata', models.PositiveIntegerField(default=0)),
                ('cobre', models.PositiveIntegerField(default=0)),
                ('electrum', models.PositiveIntegerField(default=0)),
                ('platino', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiracion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('valor', models.PositiveIntegerField(blank=True, null=True)),
                ('efecto', models.CharField(blank=True, max_length=100, null=True)),
                ('informacion', models.TextField(blank=True, max_length=2000, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='items/')),
            ],
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
                ('completada', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('principal', 'Principal'), ('secundaria', 'Secundaria'), ('opcional', 'Opcional')], default='principal', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('contenido', models.TextField(blank=True, max_length=10000, null=True)),
                ('tipo', models.CharField(choices=[('privada', 'Privada'), ('publica', 'Pública'), ('dm', 'Entre Dungeon Master y Jugador')], max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipanteCampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipanteEncuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciativa', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('vivo', 'Vivo'), ('inconsciente', 'Inconsciente'), ('muerto', 'Muerto')], default='vivo', max_length=20)),
            ],
        ),
    ]
