# Generated by Django 5.1.2 on 2025-05-01 16:21

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('dndapp', '0001_initial'),
        ('firebase_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('apodo', models.CharField(max_length=100)),
                ('biografia', models.TextField(blank=True, max_length=500, null=True)),
                ('avatar', models.ImageField(blank=True, default='avatares/default_avatar.jpg', null=True, upload_to='avatares/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('color_fondo', colorfield.fields.ColorField(default='#f25f29', image_field=None, max_length=25, samples=None)),
                ('color_texto', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.AddField(
            model_name='encuentro',
            name='campana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuentros', to='dndapp.campana'),
        ),
        migrations.AddField(
            model_name='enemigo',
            name='alineamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dndapp.alineamiento'),
        ),
        migrations.AddField(
            model_name='enemigo',
            name='idiomas',
            field=models.ManyToManyField(blank=True, to='dndapp.idioma'),
        ),
        migrations.AddField(
            model_name='campana',
            name='imagenes',
            field=models.ManyToManyField(blank=True, to='dndapp.imagencampana'),
        ),
        migrations.AddField(
            model_name='inventarioparty',
            name='campana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='dndapp.campana'),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='campana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='dndapp.campana'),
        ),
        migrations.AddField(
            model_name='inventariopersonaje',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dndapp.item'),
        ),
        migrations.AddField(
            model_name='inventarioparty',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dndapp.item'),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipamiento', to='dndapp.item'),
        ),
        migrations.AddField(
            model_name='consumible',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumible', to='dndapp.item'),
        ),
        migrations.AddField(
            model_name='arma',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arma', to='dndapp.item'),
        ),
        migrations.AddField(
            model_name='mision',
            name='campana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misiones', to='dndapp.campana'),
        ),
        migrations.AddField(
            model_name='nota',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='participantecampana',
            name='campana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dndapp.campana'),
        ),
        migrations.AddField(
            model_name='participanteencuentro',
            name='encuentro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='dndapp.encuentro'),
        ),
        migrations.AddField(
            model_name='participanteencuentro',
            name='enemigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dndapp.enemigo'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='enemigos',
            field=models.ManyToManyField(blank=True, through='dndapp.ParticipanteEncuentro', to='dndapp.enemigo'),
        ),
        migrations.AddField(
            model_name='participantecampana',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dndapp.perfil'),
        ),
        migrations.AddField(
            model_name='nota',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dndapp.perfil'),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dndapp.perfil'),
        ),
        migrations.AddField(
            model_name='campana',
            name='dungeon_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanas_creadas', to='dndapp.perfil'),
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, default='pjs/default_pj.jpg', null=True, upload_to='pjs/')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=50)),
                ('subraza', models.CharField(blank=True, max_length=50, null=True)),
                ('clase', models.CharField(max_length=50)),
                ('subclase', models.CharField(blank=True, max_length=50, null=True)),
                ('nivel', models.PositiveIntegerField()),
                ('xp', models.PositiveBigIntegerField(blank=True, null=True)),
                ('inspiracion', models.BooleanField(default=False)),
                ('vitalidad_maxima', models.IntegerField()),
                ('vitalidad_actual', models.IntegerField()),
                ('fuerza', models.IntegerField()),
                ('destreza', models.IntegerField()),
                ('constitucion', models.IntegerField()),
                ('inteligencia', models.IntegerField()),
                ('sabiduria', models.IntegerField()),
                ('carisma', models.IntegerField()),
                ('armadura_base', models.PositiveIntegerField(default=0)),
                ('color_token', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('alineamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dndapp.alineamiento')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personajes', to='dndapp.perfil')),
                ('idiomas', models.ManyToManyField(related_name='personajes', to='dndapp.idioma')),
            ],
        ),
        migrations.AddField(
            model_name='participanteencuentro',
            name='personaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dndapp.personaje'),
        ),
        migrations.AddField(
            model_name='participantecampana',
            name='personaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dndapp.personaje'),
        ),
        migrations.AddField(
            model_name='inventariopersonaje',
            name='personaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='dndapp.personaje'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='personajes',
            field=models.ManyToManyField(blank=True, through='dndapp.ParticipanteEncuentro', to='dndapp.personaje'),
        ),
        migrations.CreateModel(
            name='PersonajeNoJugable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='pnjs/')),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnjs', to='dndapp.campana')),
            ],
        ),
        migrations.CreateModel(
            name='RolCampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('permisos', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
        ),
        migrations.AddField(
            model_name='participantecampana',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dndapp.rolcampana'),
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en curso', 'En curso'), ('finalizada', 'Finalizada')], default='programada', max_length=50)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='dndapp.campana')),
                ('imagenes', models.ManyToManyField(blank=True, to='dndapp.imagencampana')),
            ],
        ),
        migrations.AddField(
            model_name='encuentro',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuentros', to='dndapp.sesion'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dndapp.tag'),
        ),
        migrations.AddField(
            model_name='hechizo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dndapp.tag'),
        ),
        migrations.CreateModel(
            name='Tesoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rareza', models.CharField(blank=True, choices=[('comun', 'Común'), ('poco_comun', 'Poco común'), ('raro', 'Raro'), ('muy_raro', 'Muy raro'), ('legendario', 'Legendario'), ('artefacto', 'Artefacto')], max_length=50, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tesoro', to='dndapp.item')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='participantecampana',
            unique_together={('perfil', 'campana')},
        ),
    ]
