# Generated by Django 5.1.2 on 2025-05-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuentro',
            name='sesion',
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipo',
            field=models.CharField(choices=[('privada', 'Privada'), ('publica', 'Pública'), ('dm', 'DM y Jugador')], max_length=10),
        ),
    ]
