# Generated by Django 5.1.2 on 2025-05-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndapp', '0004_participanteencuentro_turno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuentro',
            old_name='fecha_creacion',
            new_name='fecha_fin',
        ),
    ]
