# Generated by Django 5.1.2 on 2025-05-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndapp', '0005_rename_fecha_creacion_encuentro_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
    ]
