# Generated by Django 5.1.2 on 2025-05-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndapp', '0006_alter_encuentro_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemigo',
            name='vitalidad_maxima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participanteencuentro',
            name='vitalidad_actual_enemigo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participanteencuentro',
            name='estado',
            field=models.CharField(choices=[('vivo', 'Vivo'), ('inconsciente', 'Inconsciente'), ('muerto', 'Muerto'), ('otro', 'Otro')], default='vivo', max_length=20),
        ),
    ]
