# Generated by Django 5.1.2 on 2025-05-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndapp', '0007_enemigo_vitalidad_maxima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemigo',
            name='puntos_vida',
        ),
    ]
