# Generated by Django 5.1.2 on 2025-05-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndapp', '0008_remove_enemigo_puntos_vida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada')], default='programada', max_length=50),
        ),
    ]
