# Generated by Django 5.1.2 on 2025-05-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndapp', '0009_alter_sesion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
