# Generated by Django 5.1.2 on 2025-05-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndapp', '0010_alter_encuentro_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='competencias',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
