# Generated by Django 5.1.2 on 2025-06-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndapp', '0011_personaje_competencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemigo',
            name='alineamiento',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='alineamiento',
        ),
    ]
