# Generated by Django 5.1.2 on 2025-06-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndapp', '0012_remove_enemigo_alineamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='bono_competencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
