# Generated by Django 5.1.2 on 2025-06-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndapp', '0013_personaje_bono_competencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemigo',
            name='competencias',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='enemigo',
            name='imagen',
            field=models.ImageField(blank=True, default='enemigos/default_enemigo.jpg', null=True, upload_to='enemigos/'),
        ),
    ]
