# Generated by Django 5.1.2 on 2025-06-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndapp', '0014_enemigo_competencias_alter_enemigo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemigo',
            name='puntaje_dados',
        ),
        migrations.RemoveField(
            model_name='enemigo',
            name='puntaje_fijo',
        ),
        migrations.AddField(
            model_name='enemigo',
            name='puntaje',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
