# Generated by Django 5.1.2 on 2025-06-03 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndapp', '0015_remove_enemigo_puntaje_dados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemigo',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enemigos', to='dndapp.perfil'),
        ),
    ]
